// # Generated by MongoDB Atlas onboarding.
// # This file contains sensitive credentials.
// # DO NOT commit this file to version control.
// # Store it securely (e.g. use a password manager or secrets vault).

// MONGODB_USERNAME="wwwsmritipatel123_db_user"
// MONGODB_PASSWORD="qbfaVUOfkE2RydFD"
// MONGODB_URI="mongodb+srv://wwwsmritipatel123_db_user:qbfaVUOfkE2RydFD@studentdatabase.wpbqzor.mongodb.net"
//wwwsmritipatel123_db_user
//qbfaVUOfkE2RydFD
//mongosh "mongodb+srv://studentdatabase.wpbqzor.mongodb.net/" --apiVersion 1 --username wwwsmritipatel123_db_user